---
# tasks file for stunnel-role
- name: Install SSL backend
  apt:
    name: openssl
    update_cache: yes

- name: Install package
  apt: 
    name: stunnel4 
    force: yes

- name: Enable stunnel
  lineinfile:
    dest: /etc/default/stunnel4
    state: present
    regexp: ENABLED=
    line: ENABLED=1

- include: certificate.yml
  when: '{{stunnel_certificate_generation}}'

- name: Stunnel configuration
  template:
    src: stunnel.conf.j2
    dest: /etc/stunnel/stunnel.conf

- name: Start stunnel service
  service:
    name: stunnel4
    state: started