---
# tasks file for stunnel-role
- name: Install SSL backend
  package:
    name: openssl
    update_cache: yes
  register: install_ssl_backend

- name: Install package
  package:
    name: stunnel4 
    force: yes
  register: install_stunnel_4

- include: certificate.yml  

- name: Stunnel configuration
  template:
    src: stunnel.conf.j2
    dest: /etc/stunnel/stunnel.conf
  register: stunnel_configuration

- name: Start stunnel service
  service:
    name: stunnel4
    state: restarted
    enabled: true
  when: install_stunnel_4 is changed or stunnel_configuration is changed
